"use client";
import { useState, useEffect, useRef } from "react";
import Link from "next/link";
import jsPDF from "jspdf";
import {
  getStrikes,
  updateStrikeStatus,
  batchSendStrikes,
  getStrikeNotice,
  seedDemoStrikes,
  type Strike,
} from "@/lib/api";

// ─── helpers (unchanged from original) ──────────────────────────────────────

const statusColor = (s: string): string =>
  s === "removed" ? "#39FF14" : s === "sent" ? "#FF6B2B" : s === "acknowledged" ? "#F39C12" : s === "appealed" ? "#E74C3C" : s === "restored" ? "#E74C3C" : "#2E86DE";

const statusLabel = (s: string): string =>
  s === "draft" ? "Draft" : s === "sent" ? "Sent" : s === "acknowledged" ? "Acknowledged" : s === "removed" ? "Removed" : s === "appealed" ? "Appealed" : "Restored";

const jurisdictionNotice = (j: string): { type: string; desc: string } =>
  ({
    US: { type: "DMCA Takedown", desc: "Digital Millennium Copyright Act (17 U.S.C. § 512)" },
    EU: { type: "DSA Notice", desc: "Digital Services Act (Regulation 2022/2065)" },
    IN: { type: "IT Act Notice", desc: "Information Technology Act, 2000 (Section 79)" },
    GB: { type: "DMCA Takedown", desc: "Copyright, Designs and Patents Act 1988" },
    FR: { type: "DSA Notice", desc: "Digital Services Act (Regulation 2022/2065)" },
    DE: { type: "DSA Notice", desc: "Digital Services Act + NetzDG" },
    BR: { type: "Generic Notice", desc: "Lei do Marco Civil da Internet" },
    OTHER: { type: "Generic DMCA", desc: "Standard takedown notice" },
  } as Record<string, { type: string; desc: string }>)[j] || { type: "Generic", desc: "Standard notice" };

// ─── PDF builder (now uses real notice body from backend) ────────────────────

async function downloadStrikeNotice(strike: Strike) {
  // Fetch real notice text from backend
  const noticeData = await getStrikeNotice(strike.id);

  const pdf = new jsPDF("p", "mm", "a4");

  pdf.setFillColor(13, 5, 0);
  pdf.rect(0, 0, 210, 297, "F");
  pdf.setFillColor(231, 76, 60);
  pdf.rect(0, 0, 4, 297, "F");
  pdf.setFillColor(231, 76, 60);
  pdf.rect(4, 0, 206, 2, "F");

  pdf.setFontSize(9);
  pdf.setTextColor(231, 76, 60);
  pdf.text("PHANTRACE LEGAL", 195, 15, { align: "right" });

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(20);
  pdf.setTextColor(255, 255, 255);
  const noticeTitle = noticeData.notice_type
    ? `${noticeData.notice_type} Takedown`
    : jurisdictionNotice(strike.jurisdiction).type;
  pdf.text(noticeTitle, 15, 28);

  pdf.setDrawColor(231, 76, 60);
  pdf.setLineWidth(0.4);
  pdf.roundedRect(15, 33, 70, 6, 2, 2, "D");
  pdf.setFontSize(8);
  pdf.setTextColor(231, 76, 60);
  pdf.text("TAKEDOWN NOTICE", 50, 37.5, { align: "center" });

  pdf.setDrawColor(231, 76, 60);
  pdf.setLineWidth(0.4);
  pdf.line(15, 45, 195, 45);

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(9);
  pdf.setTextColor(200, 200, 200);
  pdf.text(noticeData.citation || jurisdictionNotice(strike.jurisdiction).desc, 15, 55);

  let y = 70;
  const caseDetails = [
    ["STRIKE ID", strike.id],
    ["DETECTION ID", strike.detectionId || "N/A"],
    ["CONTENT TITLE", strike.title],
    ["INFRINGING ACCOUNT", strike.account],
    ["PLATFORM", strike.platform],
    ["VIOLATION COUNT", `${strike.violationCount}x`],
    ["REPEAT OFFENDER", strike.isRepeatOffender ? "YES — ESCALATED" : "NO"],
  ];

  caseDetails.forEach(([label, value]) => {
    pdf.setFontSize(8);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(120, 120, 120);
    pdf.text(label, 15, y);
    pdf.setFontSize(10);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(255, 255, 255);
    pdf.text(value, 100, y);
    y += 8;
  });

  y += 5;
  pdf.setDrawColor(231, 76, 60);
  pdf.setLineWidth(0.4);
  pdf.line(15, y, 195, y);

  y += 8;
  pdf.setFontSize(9);
  pdf.setFont("helvetica", "normal");
  pdf.setTextColor(200, 200, 200);

  const bodyText = noticeData.notice_body || `This is a ${noticeTitle} notice of copyright infringement. The content identified above infringes the intellectual property rights of the rights holder.

Platform: You are requested to remove the infringing content and disable access to it within the timeframe specified by applicable law.

Account Holder: You have the right to file a counter-notice if you believe this takedown was filed in error.

Repeat Offender Status: ${strike.isRepeatOffender ? "This account has violated multiple times. Legal escalation may apply." : "First-time violation on record."}`;

  const splitText = pdf.splitTextToSize(bodyText, 170);
  pdf.text(splitText, 15, y);

  y = 260;
  pdf.setDrawColor(231, 76, 60);
  pdf.setLineWidth(0.4);
  pdf.line(15, y, 195, y);

  pdf.setFontSize(8);
  pdf.setFont("helvetica", "normal");
  pdf.setTextColor(100, 100, 100);
  pdf.text("Generated by PhanTrace Legal System", 15, y + 10);
  pdf.setTextColor(231, 76, 60);
  pdf.text(new Date().toLocaleDateString(), 195, y + 10, { align: "right" });

  pdf.save(`strike-${strike.id}.pdf`);
}

// ─── helpers to format dates from ISO strings ────────────────────────────────

function formatRelativeDate(isoString?: string | null): string {
  if (!isoString) return "";
  try {
    const diff = Date.now() - new Date(isoString).getTime();
    const mins = Math.floor(diff / 60000);
    if (mins < 1) return "just now";
    if (mins < 60) return `${mins} min ago`;
    const hrs = Math.floor(mins / 60);
    if (hrs < 24) return `${hrs} hour${hrs > 1 ? "s" : ""} ago`;
    const days = Math.floor(hrs / 24);
    return `${days} day${days > 1 ? "s" : ""} ago`;
  } catch {
    return "";
  }
}

// ─── component ───────────────────────────────────────────────────────────────

export default function StrikePage() {
  const [strikes, setStrikes] = useState<Strike[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [selectedStrikes, setSelectedStrikes] = useState<string[]>([]);
  const [filterStatus, setFilterStatus] = useState<string>("all");
  const [filterJurisdiction, setFilterJurisdiction] = useState<string>("all");
  const [searchTerm, setSearchTerm] = useState("");
  const [showBatchActions, setShowBatchActions] = useState(false);

  // ── fetch strikes on mount ──────────────────────────────────────────────
  useEffect(() => {
    loadStrikes();
  }, []);

  async function loadStrikes() {
    setLoading(true);
    setError(null);
    try {
      const res = await getStrikes();
      if (res.status === "success" && res.strikes) {
        setStrikes(res.strikes);
      } else {
        setError(res.error || "Failed to load strikes");
      }
    } catch (e) {
      setError("Could not reach backend");
    } finally {
      setLoading(false);
    }
  }

  // ── filtering (same logic as before) ────────────────────────────────────
  const filtered = strikes.filter(
    (s) =>
      (filterStatus === "all" || s.status === filterStatus) &&
      (filterJurisdiction === "all" || s.jurisdiction === filterJurisdiction) &&
      (searchTerm === "" ||
        s.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
        s.account.toLowerCase().includes(searchTerm.toLowerCase()))
  );

  function toggleStrike(id: string) {
    setSelectedStrikes((prev) => (prev.includes(id) ? prev.filter((x) => x !== id) : [...prev, id]));
  }

  function toggleAll() {
    setSelectedStrikes(selectedStrikes.length === filtered.length ? [] : filtered.map((s) => s.id));
  }

  // ── update status — hits backend, then refreshes local state ─────────────
  async function handleStatusUpdate(id: string, newStatus: Strike["status"]) {
    const res = await updateStrikeStatus(id, newStatus);
    if (res.status === "success" && res.strike) {
      setStrikes((prev) =>
        prev.map((s) =>
          s.id === id
            ? {
                ...s,
                status: newStatus,
                sentDate: res.strike!.sentDate ?? s.sentDate,
                removedDate: res.strike!.removedDate ?? s.removedDate,
                violationCount: res.strike!.violationCount ?? s.violationCount,
                isRepeatOffender: res.strike!.isRepeatOffender ?? s.isRepeatOffender,
              }
            : s
        )
      );
    }
  }

  // ── batch send — hits backend, then refreshes local state ────────────────
  async function handleBatchSend() {
    const draftIds = selectedStrikes.filter((id) => strikes.find((s) => s.id === id)?.status === "draft");
    if (draftIds.length === 0) return;
    const res = await batchSendStrikes(draftIds);
    if (res.status === "success") {
      setStrikes((prev) =>
        prev.map((s) =>
          draftIds.includes(s.id) ? { ...s, status: "sent", sentDate: new Date().toISOString() } : s
        )
      );
      setSelectedStrikes([]);
    }
  }

  // ─────────────────────────────────────────────────────────────────────────

  const navLogo = (
    <Link href="/" style={{ textDecoration: "none", display: "flex", alignItems: "center", gap: "0.5rem" }}>
      <img src="/logo.png" alt="" style={{ height: "28px", width: "28px" }} />
      <span style={{ fontFamily: "'Inter', sans-serif", fontSize: "1.5rem", fontWeight: 900, color: "#fff", letterSpacing: "-1px" }}>
        Phan<span style={{ color: "#FF6B2B" }}>Trace</span>
      </span>
    </Link>
  );

  return (
    <main style={{ minHeight: "100vh", background: "#0d0500", fontFamily: "'DM Sans', sans-serif", color: "rgba(255,255,255,0.85)", position: "relative", overflow: "hidden" }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@900&family=Bebas+Neue&family=DM+Sans:wght@300;400;500;600&family=DM+Mono:wght@400;500&display=swap');
        .strike-item { animation: slideIn 0.4s ease forwards; }
        @keyframes slideIn { from { opacity:0; transform:translateX(20px); } to { opacity:1; transform:translateX(0); } }
        .status-badge { transition: all 0.2s; }
        .action-btn { transition: all 0.2s; }
        .action-btn:hover { transform: translateY(-2px); }
        ::-webkit-scrollbar { width: 3px; }
        ::-webkit-scrollbar-thumb { background: rgba(255,107,43,0.2); border-radius: 2px; }
      `}</style>

      <img src="/strikebg1.jpg" alt="" className="absolute inset-0 w-full h-full object-cover scale-105" style={{ zIndex: 0 }} />
      <div style={{ position: "fixed", inset: 0, backgroundImage: "linear-gradient(rgba(255,107,43,0.03) 1px, transparent 1px), linear-gradient(90deg, rgba(255,107,43,0.03) 1px, transparent 1px)", backgroundSize: "60px 60px", zIndex: 0, pointerEvents: "none" }} />

      {/* Navbar */}
      <nav style={{ position: "relative", zIndex: 10, display: "flex", justifyContent: "space-between", alignItems: "center", padding: "1.4rem 3rem", borderBottom: "1px solid rgba(255,107,43,0.15)", background: "rgba(13,5,0,0.8)", backdropFilter: "blur(12px)" }}>
        {navLogo}
        <div style={{ display: "flex", gap: "2rem", alignItems: "center" }}>
          {[["Home", "/"], ["Upload", "/upload"], ["Dashboard", "/dashboard"], ["Detections", "/detections"], ["Strike", "/strike"]].map(([label, href]) => (
            <Link key={label} href={href} style={{ color: label === "Strike" ? "#FF6B2B" : "rgba(255,255,255,0.35)", textDecoration: "none", fontSize: "0.75rem", fontWeight: 500, letterSpacing: "0.12em", textTransform: "uppercase" }}>
              {label}
            </Link>
          ))}
          <button style={{ background: "transparent", border: "1px solid rgba(255,107,43,0.2)", color: "rgba(255,255,255,0.4)", padding: "0.45rem 1.2rem", borderRadius: "999px", fontSize: "0.72rem", cursor: "pointer", letterSpacing: "0.08em", fontFamily: "'DM Sans', sans-serif" }}>
            Sign In
          </button>
        </div>
      </nav>

      {/* Page content */}
      <div style={{ position: "relative", zIndex: 1, padding: "2rem 2.5rem", display: "flex", flexDirection: "column", gap: "1.5rem" }}>

        {/* Header */}
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-end" }}>
          <div>
            <p style={{ fontFamily: "'DM Mono', monospace", fontSize: "0.8rem", color: "#E74C3C", letterSpacing: "0.2em", textTransform: "uppercase", marginBottom: "0.3rem", fontWeight: 700 }}>LEGAL ENFORCEMENT</p>
            <h1 style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: "2.8rem", color: "#fff", lineHeight: 1, letterSpacing: "0.02em" }}>
              STRIKE <span style={{ color: "#E74C3C" }}>COMMAND</span>
            </h1>
          </div>
          <div style={{ display: "flex", gap: "0.75rem" }}>
            <button
              onClick={() => setShowBatchActions(!showBatchActions)}
              style={{ background: selectedStrikes.length > 0 ? "#E74C3C" : "rgba(231,76,60,0.2)", color: "#fff", border: "none", borderRadius: "8px", padding: "0.7rem 1.2rem", fontFamily: "'DM Mono', monospace", fontSize: "0.65rem", letterSpacing: "0.1em", textTransform: "uppercase", cursor: "pointer", transition: "all 0.2s" }}>
              {selectedStrikes.length > 0 ? `BATCH ACTIONS (${selectedStrikes.length})` : "SELECT STRIKES"}
            </button>
          </div>
        </div>

        {/* Loading / error states */}
        {loading && (
          <div style={{ padding: "2rem", textAlign: "center", color: "rgba(255,255,255,0.4)", fontFamily: "'DM Mono', monospace", fontSize: "0.7rem", letterSpacing: "0.1em" }}>
            LOADING STRIKES...
          </div>
        )}
        {error && !loading && (
          <div style={{ background: "rgba(231,76,60,0.1)", border: "1px solid rgba(231,76,60,0.3)", borderRadius: "8px", padding: "1rem 1.25rem", fontFamily: "'DM Mono', monospace", fontSize: "0.7rem", color: "#E74C3C", letterSpacing: "0.08em" }}>
            ⚠ {error} —{" "}
            <span onClick={loadStrikes} style={{ cursor: "pointer", textDecoration: "underline" }}>
              retry
            </span>
          </div>
        )}

        {/* Stats */}
        {!loading && (
          <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: "1rem" }}>
            {[
              { label: "Total Strikes", value: strikes.length, accent: false },
              { label: "Removed", value: strikes.filter((s) => s.status === "removed").length, accent: true },
              { label: "In Progress", value: strikes.filter((s) => ["sent", "acknowledged"].includes(s.status)).length, accent: false },
              { label: "Repeat Offenders", value: strikes.filter((s) => s.isRepeatOffender).length, accent: true },
            ].map(({ label, value, accent }) => (
              <div key={label} style={{ background: "rgba(22,11,2,0.85)", border: `1px solid ${accent ? "rgba(231,76,60,0.3)" : "rgba(255,107,43,0.1)"}`, borderRadius: "12px", padding: "1.25rem 1.5rem", display: "flex", flexDirection: "column", gap: "0.4rem" }}>
                <p style={{ fontFamily: "'DM Mono', monospace", fontSize: "0.8rem", color: "rgba(255,255,255,0.39)", letterSpacing: "0.18em", textTransform: "uppercase" }}>{label}</p>
                <p style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: "2rem", color: accent ? "#E74C3C" : "#fff", lineHeight: 1 }}>{value}</p>
                {accent && <div style={{ height: "2px", width: "24px", background: "#E74C3C", borderRadius: "1px" }} />}
              </div>
            ))}
          </div>
        )}

        {/* Filters & Search */}
        <div style={{ display: "flex", gap: "1rem", alignItems: "center", flexWrap: "wrap" }}>
          <input
            type="text"
            placeholder="Search by title or account..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            style={{ flex: 1, minWidth: "250px", background: "rgba(22,11,2,0.9)", border: "1px solid rgba(255,107,43,0.15)", borderRadius: "8px", padding: "0.7rem 1rem", color: "#fff", fontFamily: "'DM Sans', sans-serif", fontSize: "0.8rem" }}
          />
          <select value={filterStatus} onChange={(e) => setFilterStatus(e.target.value)} style={{ background: "rgba(22,11,2,0.9)", border: "1px solid rgba(255,107,43,0.15)", borderRadius: "8px", padding: "0.7rem 1rem", color: "rgba(255,255,255,0.7)", fontFamily: "'DM Sans', sans-serif", fontSize: "0.8rem", cursor: "pointer" }}>
            <option value="all">All Status</option>
            <option value="draft">Draft</option>
            <option value="sent">Sent</option>
            <option value="acknowledged">Acknowledged</option>
            <option value="removed">Removed</option>
            <option value="appealed">Appealed</option>
            <option value="restored">Restored</option>
          </select>
          <select value={filterJurisdiction} onChange={(e) => setFilterJurisdiction(e.target.value)} style={{ background: "rgba(22,11,2,0.9)", border: "1px solid rgba(255,107,43,0.15)", borderRadius: "8px", padding: "0.7rem 1rem", color: "rgba(255,255,255,0.7)", fontFamily: "'DM Sans', sans-serif", fontSize: "0.8rem", cursor: "pointer" }}>
            <option value="all">All Jurisdictions</option>
            <option value="US">US (DMCA)</option>
            <option value="EU">EU (DSA)</option>
            <option value="IN">India (IT Act)</option>
            <option value="GB">UK</option>
            <option value="FR">France (DSA)</option>
            <option value="DE">Germany (DSA)</option>
            <option value="BR">Brazil</option>
            <option value="OTHER">Other</option>
          </select>
        </div>

        {/* Batch Actions Bar */}
        {showBatchActions && selectedStrikes.length > 0 && (
          <div style={{ background: "rgba(231,76,60,0.1)", border: "1px solid rgba(231,76,60,0.3)", borderRadius: "12px", padding: "1.25rem", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
            <span style={{ fontFamily: "'DM Mono', monospace", fontSize: "0.7rem", color: "#E74C3C", letterSpacing: "0.1em" }}>
              {selectedStrikes.length} STRIKE(S) SELECTED
            </span>
            <div style={{ display: "flex", gap: "0.75rem" }}>
              <button
                onClick={handleBatchSend}
                style={{ background: "#E74C3C", color: "#fff", border: "none", borderRadius: "6px", padding: "0.6rem 1rem", fontFamily: "'DM Mono', monospace", fontSize: "0.62rem", letterSpacing: "0.08em", textTransform: "uppercase", cursor: "pointer" }}>
                Send All →
              </button>
              <button onClick={() => setSelectedStrikes([])} style={{ background: "transparent", color: "#E74C3C", border: "1px solid #E74C3C", borderRadius: "6px", padding: "0.6rem 1rem", fontFamily: "'DM Mono', monospace", fontSize: "0.62rem", letterSpacing: "0.08em", textTransform: "uppercase", cursor: "pointer" }}>
                Clear
              </button>
            </div>
          </div>
        )}

        {/* Strikes Table */}
        {!loading && (
          <div style={{ background: "rgba(16,8,2,0.9)", border: "1px solid rgba(255,107,43,0.15)", borderRadius: "16px", padding: "1.25rem 1.5rem", overflow: "auto" }}>
            <div style={{ display: "flex", flexDirection: "column", gap: "0" }}>
              {/* Header row */}
              <div style={{ display: "grid", gridTemplateColumns: "40px 2fr 1.2fr 1fr 1fr 1.2fr 80px", gap: "1rem", padding: "0.75rem", marginBottom: "0.5rem", borderBottom: "1px solid rgba(255,107,43,0.15)" }}>
                <input type="checkbox" checked={selectedStrikes.length === filtered.length && filtered.length > 0} onChange={toggleAll} style={{ cursor: "pointer", accentColor: "#E74C3C" }} />
                {["Content", "Account", "Platform", "Notice", "Status", "Actions"].map((h) => (
                  <span key={h} style={{ fontFamily: "'DM Mono', monospace", fontSize: "0.8rem", color: "rgba(255,255,255,0.37)", letterSpacing: "0.15em", textTransform: "uppercase" }}>{h}</span>
                ))}
              </div>

              {filtered.map((strike, i) => (
                <div
                  key={strike.id}
                  className="strike-item"
                  style={{ display: "grid", gridTemplateColumns: "40px 2fr 1.2fr 1fr 1fr 1.2fr 80px", gap: "1rem", padding: "0.75rem", borderRadius: "8px", background: selectedStrikes.includes(strike.id) ? "rgba(231,76,60,0.08)" : i % 2 === 0 ? "rgba(255,107,43,0.02)" : "transparent", border: selectedStrikes.includes(strike.id) ? "1px solid rgba(231,76,60,0.2)" : "1px solid transparent", transition: "all 0.2s", alignItems: "center" }}
                  onMouseEnter={(e) => { if (!selectedStrikes.includes(strike.id)) { e.currentTarget.style.background = "rgba(255,107,43,0.06)"; e.currentTarget.style.borderColor = "rgba(255,107,43,0.15)"; } }}
                  onMouseLeave={(e) => { if (!selectedStrikes.includes(strike.id)) { e.currentTarget.style.background = i % 2 === 0 ? "rgba(255,107,43,0.02)" : "transparent"; e.currentTarget.style.borderColor = "transparent"; } }}>
                  <input type="checkbox" checked={selectedStrikes.includes(strike.id)} onChange={() => toggleStrike(strike.id)} style={{ cursor: "pointer", accentColor: "#E74C3C" }} />
                  <span style={{ fontSize: "0.78rem", color: "#fff", fontWeight: 500, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{strike.title}</span>
                  <span style={{ fontFamily: "'DM Mono', monospace", fontSize: "0.78rem", color: "rgba(255,255,255,0.4)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{strike.account}</span>
                  <span style={{ fontFamily: "'DM Mono', monospace", fontSize: "0.78rem", color: "rgba(255,255,255,0.4)" }}>{strike.platform}</span>
                  <div style={{ display: "flex", alignItems: "center", gap: "0.4rem" }}>
                    <span style={{ fontFamily: "'DM Mono', monospace", fontSize: "0.78rem", color: "rgba(255,255,255,0.5)" }}>{strike.noticeType}</span>
                    {strike.isRepeatOffender && <span style={{ fontSize: "0.5rem", background: "#E74C3C", color: "#fff", padding: "0.2rem 0.4rem", borderRadius: "3px", fontWeight: "bold" }}>⚠</span>}
                  </div>
                  <span className="status-badge" style={{ fontFamily: "'DM Mono', monospace", fontSize: "0.78rem", color: statusColor(strike.status), background: `${statusColor(strike.status)}15`, padding: "0.3rem 0.6rem", borderRadius: "4px", textAlign: "center", border: `1px solid ${statusColor(strike.status)}30` }}>
                    {statusLabel(strike.status)}
                  </span>
                  <div style={{ display: "flex", gap: "0.3rem" }}>
                    {strike.status === "draft" && (
                      <button className="action-btn" onClick={() => handleStatusUpdate(strike.id, "sent")} style={{ padding: "0.3rem 0.6rem", background: "#E74C3C", color: "#fff", border: "none", borderRadius: "4px", fontFamily: "'DM Mono', monospace", fontSize: "0.78rem", cursor: "pointer", letterSpacing: "0.05em" }}>
                        Send
                      </button>
                    )}
                    {strike.status === "appealed" && (
                      <button className="action-btn" onClick={() => handleStatusUpdate(strike.id, "sent")} style={{ padding: "0.3rem 0.6rem", background: "#F39C12", color: "#fff", border: "none", borderRadius: "4px", fontFamily: "'DM Mono', monospace", fontSize: "0.78rem", cursor: "pointer", letterSpacing: "0.05em" }}>
                        Re-File
                      </button>
                    )}
                    <button className="action-btn" onClick={() => downloadStrikeNotice(strike)} style={{ padding: "0.3rem 0.6rem", background: "transparent", color: "#FF6B2B", border: "1px solid #FF6B2B", borderRadius: "4px", fontFamily: "'DM Mono', monospace", fontSize: "0.78rem", cursor: "pointer", letterSpacing: "0.05em" }}>
                      PDF
                    </button>
                  </div>
                </div>
              ))}
            </div>

            {filtered.length === 0 && !loading && (
              <div style={{ padding: "2rem", textAlign: "center", color: "rgba(255,255,255,0.3)" }}>
                <p style={{ fontFamily: "'DM Mono', monospace", fontSize: "0.65rem" }}>No strikes found</p>
              </div>
            )}
          </div>
        )}

        {/* Strike Workflow Info — unchanged */}
        <div style={{ background: "rgba(19,17,17,0.9)", border: "1px solid rgba(231,76,60,0.15)", borderRadius: "16px", padding: "1.5rem", display: "grid", gridTemplateColumns: "repeat(5, 1fr)", gap: "1rem" }}>
          {[
            { step: "Draft", icon: "✎", desc: "Prepare notice" },
            { step: "Sent", icon: "✈", desc: "Delivered to platform" },
            { step: "Acknowledged", icon: "✓", desc: "Platform received" },
            { step: "Removed", icon: "⊠", desc: "Content taken down" },
            { step: "Appeal", icon: "⚠", desc: "Contested by account" },
          ].map(({ step, icon, desc }) => (
            <div key={step} style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: "0.5rem", textAlign: "center" }}>
              <div style={{ width: "40px", height: "40px", borderRadius: "50%", background: "rgba(231,76,60,0.2)", border: "1px solid rgba(231,76,60,0.4)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "1.2rem", color: "#E74C3C" }}>
                {icon}
              </div>
              <p style={{ fontFamily: "'DM Mono', monospace", fontSize: "0.80rem", color: "rgba(255,255,255,0.7)", letterSpacing: "0.08em", textTransform: "uppercase" }}>{step}</p>
              <p style={{ fontFamily: "'DM Mono', monospace", fontSize: "0.78rem", color: "rgba(255,255,255,0.3)" }}>{desc}</p>
            </div>
          ))}
        </div>

      </div>
    </main>
  );
}